eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

cat <<EOF
Welcome to Jepsen on Docker
===========================

To run a test:
   1. control run jepsen build
   2. control run jepsen deploy
   3. sh run_test.sh
EOF

cd /jepsen/fastminiraft-jepsen
